### PR TITLE
Add missing Hauppauge firmware files

### PR DESCRIPTION
**Pull request by ich777**
- Add missing Hauppauge firmware files
  Source: https://launchpad.net/~b-rad/+archive/ubuntu/kernel+mediatree+hauppauge

### CODE REVIEW

**Comment by CvH** [comment]
any idea what version `dvb-demod-si2168-b40-01.fw` is ?

**Comment by ich777** [comment]
Oh sorry, I didn't meant to replace that file since it was already in the repository. Should I open a new PR?

My main concern was `dvb-demod-mxl692.fw` because it is needed for: Hauppauge WinTV QuadHD USB TV Tuner

**Comment by CvH** [comment]
i compared the hashes and this is the `4.0.11` version and we have already the `4.0.25` version
http://palosaari.fi/linux/v4l-dvb/firmware/Si2168/Si2168-B40/

so pls drop the change to that file :)
otherwise okay

**Comment by ich777** [comment]
@CvH done, only the three missing firmware files are now in the PR. Thank you in advance!

**Comment by ich777** [comment]
@CvH I almost forgot to ask, will this also update the [Releases](https://github.com/LibreELEC/dvb-firmware/releases)?

**Comment by Drommer** [comment]
[`dvb_driver_si2157_rom50.fw`](https://github.com/LibreELEC/dvb-firmware/blob/master/firmware/dvb_driver_si2157_rom50.fw) it's just the [`dvb-tuner-si2157-a30-01.fw`](https://github.com/LibreELEC/dvb-firmware/blob/master/firmware/dvb-tuner-si2157-a30-01.fw) firmware with a different name. The sha256sum is the same.

**Pull request merged**
