### PR TITLE
add several fws

### PR DESCRIPTION
**Pull request by CvH**
do NOT merge yet !!!

@trsqr pls have a look if something is unnecessary we don't want

### CODE REVIEW

**Comment by trsqr** [comment]
@cvh, the si2168-01 is unnecessary. It is from the time when the driver did not have support for other Si2168 versions. The driver will only load it if the Si2168-b40 firmware doesn't exist.

**Comment by CvH** [comment]
What about the b60, astromenta and dw2102?

**Comment by trsqr** [comment]
Sorry, not much experience of those. I think it's a good idea to add the firmwares though - there are certainly devices using them.

**Comment by CvH** [comment]
@trsqr si2168-01 dropped, I merge this, if you get info that something needs to get dropped just create a pr/slack-me.

**Pull request merged**
