### PR TITLE
DS3103B rename to upstream name

### PR DESCRIPTION
**Pull request by CvH**

### CODE REVIEW

**Comment by daramori** [comment]
Will this pull request be merged for LibreELEC 10.0?

I was testing one of the latest nightlies (LibreELEC-RPi2.arm-10.0-nightly-20210311-3f55efc) with a PCTV 461e v2 DVB-S adapter and this rename is needed to support the device. Without it, the journalctl log shows a missing firmware file error.

**Comment by CvH** [comment]
Can you post the dmesg?
dmesg | paste

**Comment by daramori** [comment]
Here's the dmesg when the device is plugged in without this pull request:

```
[   46.446158] usb 1-1.1.2: new high-speed USB device number 6 using dwc_otg
[   46.537126] usb 1-1.1.2: New USB device found, idVendor=2013, idProduct=0461, bcdDevice= 1.00
[   46.537148] usb 1-1.1.2: New USB device strings: Mfr=3, Product=1, SerialNumber=2
[   46.537159] usb 1-1.1.2: Product: PCTV 461
[   46.537170] usb 1-1.1.2: Manufacturer: PCTV
[   46.537181] usb 1-1.1.2: SerialNumber: XXXXXXXXXX
[   46.622997] em28xx 1-1.1.2:1.0: New device PCTV PCTV 461 @ 480 Mbps (2013:0461, interface 0, class 0)
[   46.623012] em28xx 1-1.1.2:1.0: DVB interface 0 found: isoc
[   46.679592] em28xx 1-1.1.2:1.0: chip ID is em28178
[   47.057471] em28xx 1-1.1.2:1.0: EEPROM ID = 26 00 01 00, EEPROM hash = 0xb4ae44a6
[   47.057483] em28xx 1-1.1.2:1.0: EEPROM info:
[   47.057490] em28xx 1-1.1.2:1.0:      microcode start address = 0x0004, boot configuration = 0x01
[   47.066560] em28xx 1-1.1.2:1.0:      AC97 audio (5 sample rates)
[   47.066572] em28xx 1-1.1.2:1.0:      500mA max power
[   47.066582] em28xx 1-1.1.2:1.0:      Table at offset 0x27, strings=0x148c, 0x1874, 0x0a6a
[   47.122788] em28xx 1-1.1.2:1.0: Identified as PCTV DVB-S2 Stick (461e v2) (card=104)
[   47.122805] em28xx 1-1.1.2:1.0: dvb set to isoc mode.
[   47.123187] usbcore: registered new interface driver em28xx
[   47.128463] em28xx 1-1.1.2:1.0: Binding DVB extension
[   47.181753] i2c i2c-18: Added multiplexed i2c bus 19
[   47.254715] ts2020 19-0060: Montage Technology TS2022 successfully identified
[   47.282275] a8293 18-0008: Allegro A8293 SEC successfully attached
[   47.282352] dvbdev: DVB: registering new adapter (1-1.1.2:1.0)
[   47.282365] em28xx 1-1.1.2:1.0: DVB: registering adapter 1 frontend 0 (Montage Technology M88DS3103B)...
[   47.282384] dvbdev: dvb_create_media_entity: media entity 'Montage Technology M88DS3103B' registered.
[   47.284027] dvbdev: dvb_create_media_entity: media entity 'dvb-demux' registered.
[   47.286662] m88ds3103 18-006a: found a 'Montage Technology M88DS3103B' in cold state
[   47.286745] m88ds3103 18-006a: Direct firmware load for dvb-demod-m88ds3103b.fw failed with error -2
[   47.286756] m88ds3103 18-006a: firmware file 'dvb-demod-m88ds3103b.fw' not found
[   47.291254] em28xx 1-1.1.2:1.0: DVB extension successfully initialized
[   47.291272] em28xx: Registered (Em28xx dvb Extension) extension
[   47.297723] em28xx 1-1.1.2:1.0: DVB: adapter 1 frontend 0 frequency 0 out of range (950000..2150000)
[   47.324753] em28xx 1-1.1.2:1.0: Registering input extension
[   47.386114] Registered IR keymap rc-pinnacle-pctv-hd
[   47.386652] rc rc1: PCTV DVB-S2 Stick (461e v2) as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.0/rc/rc1
[   47.386839] rc rc1: lirc_dev: driver em28xx registered at minor = 1, scancode receiver, no transmitter
[   47.386998] input: PCTV DVB-S2 Stick (461e v2) as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.0/rc/rc1/input2
[   47.387244] em28xx 1-1.1.2:1.0: Input extension successfully initialized
[   47.387254] em28xx: Registered (Em28xx Input Extension) extension
[   47.614042] input: eventlircd as /devices/virtual/input/input3
```

**Comment by CvH** [comment]
@daramori tx (likely included in LE10b2)

**Pull request merged**
